/**
 * Las Vegas Strip Walking Guide - Data Layer
 *
 * All hotels are ordered north to south along the Strip.
 * Position values represent approximate relative position (0 = north end, 100 = south end).
 * Side: "west" = left/west side of Las Vegas Blvd, "east" = right/east side.
 */

const STRIP_DATA = {
  hotels: [
    // === NORTH STRIP ===
    { id: "strat", name: "The STRAT", side: "east", zone: "north", position: 2, gaming: true,
      description: "Northern anchor of the Strip. Known for its observation tower and thrill rides." },
    { id: "sahara", name: "Sahara Las Vegas", side: "east", zone: "north", position: 6, gaming: true,
      description: "Home to a Monorail station. Recently renovated with modern rooms and restaurants." },
    { id: "fontainebleau", name: "Fontainebleau Las Vegas", side: "east", zone: "north", position: 9, gaming: true,
      description: "Luxury megaresort with 3,700+ rooms. Opened in 2023." },
    { id: "circus-circus", name: "Circus Circus", side: "west", zone: "north", position: 10, gaming: true,
      description: "Family-friendly classic with the Adventuredome theme park." },
    { id: "resorts-world", name: "Resorts World", side: "west", zone: "north", position: 14, gaming: true,
      description: "Massive resort complex featuring Hilton, Conrad, and Crockfords brands." },
    { id: "encore", name: "Encore at Wynn", side: "east", zone: "north", position: 18, gaming: true,
      description: "Luxury sister property to Wynn with its own pool deck and nightlife." },
    { id: "wynn", name: "Wynn Las Vegas", side: "east", zone: "north", position: 20, gaming: true,
      description: "Five-star luxury resort known for impeccable service and a championship golf course." },
    { id: "fashion-show", name: "Fashion Show Mall", side: "west", zone: "north", position: 21, gaming: false,
      description: "Major shopping destination with runway shows. Not a hotel but a key landmark." },

    // === MID STRIP ===
    { id: "treasure-island", name: "Treasure Island (TI)", side: "west", zone: "mid", position: 24, gaming: true,
      description: "Independently owned resort on the west side with a prime mid-Strip location." },
    { id: "venetian", name: "The Venetian", side: "east", zone: "mid", position: 25, gaming: true,
      description: "Italian-themed all-suite resort. Connected to The Palazzo via Grand Canal Shoppes." },
    { id: "palazzo", name: "The Palazzo", side: "east", zone: "mid", position: 27, gaming: true,
      description: "Luxury all-suite tower connected to The Venetian." },
    { id: "mirage", name: "The Mirage (Hard Rock - under renovation)", side: "west", zone: "mid", position: 28, gaming: false,
      description: "Currently closed for conversion to Hard Rock Hotel & Casino. Expected to reopen as a guitar-shaped tower." },
    { id: "harrahs", name: "Harrah's Las Vegas", side: "east", zone: "mid", position: 31, gaming: true,
      description: "Classic Caesars Entertainment property in the heart of the mid-Strip." },
    { id: "linq", name: "The LINQ Hotel + Experience", side: "east", zone: "mid", position: 33, gaming: true,
      description: "Home to the High Roller observation wheel and the LINQ Promenade." },
    { id: "flamingo", name: "Flamingo Las Vegas", side: "east", zone: "mid", position: 35, gaming: true,
      description: "Historic Bugsy Siegel property. Famous for its wildlife habitat with Chilean flamingos." },
    { id: "cromwell", name: "The Cromwell", side: "east", zone: "mid", position: 36, gaming: true,
      description: "Boutique hotel at the corner of Flamingo Rd and Las Vegas Blvd. Home to Drai's." },
    { id: "caesars", name: "Caesars Palace", side: "west", zone: "mid", position: 35, gaming: true,
      description: "Iconic Roman-themed mega-resort. Home to The Forum Shops and the Colosseum." },
    { id: "bellagio", name: "Bellagio", side: "west", zone: "mid", position: 39, gaming: true,
      description: "Famous for its fountain show, conservatory, and fine art gallery." },
    { id: "paris", name: "Paris Las Vegas", side: "east", zone: "mid", position: 39, gaming: true,
      description: "French-themed resort with a half-scale Eiffel Tower replica." },
    { id: "horseshoe", name: "Horseshoe Las Vegas", side: "east", zone: "mid", position: 40, gaming: true,
      description: "Formerly Bally's. Home of the World Series of Poker." },
    { id: "cosmopolitan", name: "The Cosmopolitan", side: "west", zone: "mid", position: 42, gaming: true,
      description: "Trendy luxury resort known for its speakeasies, art, and Marquee nightclub." },
    { id: "planet-hollywood", name: "Planet Hollywood", side: "east", zone: "mid", position: 43, gaming: true,
      description: "Entertainment-themed resort featuring the Miracle Mile Shops." },

    // === SOUTH STRIP ===
    { id: "waldorf", name: "Waldorf Astoria", side: "west", zone: "south", position: 47, gaming: false,
      description: "Non-gaming luxury high-rise. Part of the CityCenter complex." },
    { id: "aria", name: "Aria Resort & Casino", side: "west", zone: "south", position: 49, gaming: true,
      description: "Modern luxury resort in CityCenter. Connected to free Aria Express tram." },
    { id: "vdara", name: "Vdara Hotel & Spa", side: "west", zone: "south", position: 48, gaming: false,
      description: "Non-gaming, non-smoking luxury hotel in CityCenter." },
    { id: "crystals", name: "The Shops at Crystals", side: "west", zone: "south", position: 47, gaming: false,
      description: "High-end shopping center in CityCenter. Tram stop for Aria Express." },
    { id: "park-mgm", name: "Park MGM", side: "west", zone: "south", position: 53, gaming: true,
      description: "Only fully smoke-free casino on the Strip. Near T-Mobile Arena." },
    { id: "ny-ny", name: "New York-New York", side: "west", zone: "south", position: 56, gaming: true,
      description: "NYC-themed resort with a roller coaster and Brooklyn Bridge replica." },
    { id: "mgm-grand", name: "MGM Grand", side: "east", zone: "south", position: 57, gaming: true,
      description: "One of the world's largest hotels. Home to a Monorail station and major shows." },
    { id: "excalibur", name: "Excalibur", side: "west", zone: "south", position: 63, gaming: true,
      description: "Medieval castle-themed resort. Connected via walkway and tram to Luxor and Mandalay Bay." },
    { id: "tropicana-site", name: "Tropicana Site (A's Stadium)", side: "east", zone: "south", position: 63, gaming: false,
      description: "Former Tropicana hotel, now demolished. Future site of the Oakland A's baseball stadium (opening ~2028)." },
    { id: "luxor", name: "Luxor", side: "west", zone: "south", position: 68, gaming: true,
      description: "Iconic pyramid-shaped hotel with a sky beam visible for miles." },
    { id: "delano", name: "Delano Las Vegas", side: "west", zone: "south", position: 72, gaming: false,
      description: "All-suite luxury hotel connected to Mandalay Bay." },
    { id: "mandalay-bay", name: "Mandalay Bay", side: "west", zone: "south", position: 75, gaming: true,
      description: "Southern anchor of the Strip. Features a beach wave pool, aquarium, and convention center." },
  ],

  /**
   * Connections between hotels/locations.
   * type: "indoor_walkway" | "pedestrian_bridge" | "free_tram" | "monorail" | "sidewalk"
   * walkMinutes: approximate walking time in minutes
   * cost: "free" | dollar amount
   */
  connections: [
    // === INDOOR WALKWAYS (climate-controlled, no crossing streets) ===
    { from: "wynn", to: "encore", type: "indoor_walkway", walkMinutes: 3,
      description: "Connected through the Wynn resort interior." },
    { from: "venetian", to: "palazzo", type: "indoor_walkway", walkMinutes: 5,
      description: "Connected via the Grand Canal Shoppes. Enjoy gondola rides and Italian-style shops along the way." },
    { from: "paris", to: "horseshoe", type: "indoor_walkway", walkMinutes: 4,
      description: "Internally connected properties (same ownership). Walk through shared corridors." },
    { from: "bellagio", to: "cosmopolitan", type: "indoor_walkway", walkMinutes: 5,
      description: "Indoor walkway connecting the two properties on the west side." },
    { from: "cosmopolitan", to: "crystals", type: "indoor_walkway", walkMinutes: 3,
      description: "Pedestrian bridge/walkway from Cosmopolitan into Crystals shopping center." },
    { from: "crystals", to: "aria", type: "indoor_walkway", walkMinutes: 3,
      description: "Walk through Crystals shopping center directly into Aria." },
    { from: "crystals", to: "waldorf", type: "indoor_walkway", walkMinutes: 3,
      description: "Connected through the CityCenter complex." },
    { from: "aria", to: "vdara", type: "indoor_walkway", walkMinutes: 4,
      description: "Connected within the CityCenter complex." },
    { from: "mandalay-bay", to: "delano", type: "indoor_walkway", walkMinutes: 3,
      description: "Delano is directly connected to Mandalay Bay's lobby level." },
    { from: "mandalay-bay", to: "luxor", type: "indoor_walkway", walkMinutes: 7,
      description: "Indoor walkway through the shopping area between the two resorts." },
    { from: "luxor", to: "excalibur", type: "indoor_walkway", walkMinutes: 5,
      description: "Indoor walkway connecting Luxor and Excalibur." },
    { from: "harrahs", to: "linq", type: "indoor_walkway", walkMinutes: 4,
      description: "Connected through the LINQ Promenade corridor." },
    { from: "flamingo", to: "linq", type: "indoor_walkway", walkMinutes: 4,
      description: "Connected via the LINQ Promenade area." },
    { from: "caesars", to: "cromwell", type: "indoor_walkway", walkMinutes: 5,
      description: "Connected on the east side of Caesars near the Flamingo Rd intersection." },
    { from: "mgm-grand", to: "ny-ny", type: "pedestrian_bridge", walkMinutes: 5,
      description: "Pedestrian bridge across Tropicana Ave connecting the two properties." },

    // === PEDESTRIAN BRIDGES (overhead, crossing Las Vegas Blvd) ===
    { from: "wynn", to: "fashion-show", type: "pedestrian_bridge", walkMinutes: 4,
      description: "Overhead bridge at Spring Mountain Rd / Sands Ave crossing Las Vegas Blvd." },
    { from: "venetian", to: "treasure-island", type: "pedestrian_bridge", walkMinutes: 5,
      description: "Overhead bridge at Spring Mountain Rd / Sands Ave crossing Las Vegas Blvd." },
    { from: "venetian", to: "fashion-show", type: "pedestrian_bridge", walkMinutes: 4,
      description: "Overhead bridge at Spring Mountain Rd / Sands Ave." },
    { from: "caesars", to: "flamingo", type: "pedestrian_bridge", walkMinutes: 5,
      description: "Overhead bridge at Flamingo Rd crossing Las Vegas Blvd." },
    { from: "caesars", to: "horseshoe", type: "pedestrian_bridge", walkMinutes: 5,
      description: "Overhead bridge at Flamingo Rd crossing Las Vegas Blvd." },
    { from: "bellagio", to: "horseshoe", type: "pedestrian_bridge", walkMinutes: 4,
      description: "Overhead bridge at Flamingo Rd crossing Las Vegas Blvd. Great spot to watch the Bellagio fountains." },
    { from: "bellagio", to: "caesars", type: "pedestrian_bridge", walkMinutes: 5,
      description: "Overhead bridge crossing Las Vegas Blvd near Flamingo Rd." },
    { from: "cosmopolitan", to: "planet-hollywood", type: "pedestrian_bridge", walkMinutes: 4,
      description: "Direct overhead bridge at Harmon Ave crossing Las Vegas Blvd." },
    { from: "excalibur", to: "tropicana-site", type: "pedestrian_bridge", walkMinutes: 4,
      description: "Overhead bridge at Tropicana Ave crossing Las Vegas Blvd." },
    { from: "excalibur", to: "ny-ny", type: "pedestrian_bridge", walkMinutes: 4,
      description: "Overhead bridge at Tropicana Ave." },
    { from: "mgm-grand", to: "tropicana-site", type: "pedestrian_bridge", walkMinutes: 4,
      description: "Overhead bridge at Tropicana Ave crossing Las Vegas Blvd." },
    { from: "mgm-grand", to: "excalibur", type: "pedestrian_bridge", walkMinutes: 5,
      description: "Overhead bridge at Tropicana Ave crossing Las Vegas Blvd." },

    // === SIDEWALK CONNECTIONS (same side of the street, walking along Las Vegas Blvd) ===
    { from: "strat", to: "sahara", type: "sidewalk", walkMinutes: 8,
      description: "Walk south along the east sidewalk of Las Vegas Blvd." },
    { from: "sahara", to: "fontainebleau", type: "sidewalk", walkMinutes: 5,
      description: "Walk south along the east sidewalk." },
    { from: "fontainebleau", to: "encore", type: "sidewalk", walkMinutes: 8,
      description: "Walk south along the east sidewalk. Resorts World is across the street on the west side." },
    { from: "circus-circus", to: "resorts-world", type: "sidewalk", walkMinutes: 6,
      description: "Walk south along the west sidewalk of Las Vegas Blvd." },
    { from: "resorts-world", to: "fashion-show", type: "sidewalk", walkMinutes: 8,
      description: "Walk south along the west sidewalk." },
    { from: "fashion-show", to: "treasure-island", type: "sidewalk", walkMinutes: 3,
      description: "Walk south along the west sidewalk. They are adjacent." },
    { from: "encore", to: "wynn", type: "sidewalk", walkMinutes: 2,
      description: "Adjacent properties on the east sidewalk." },
    { from: "wynn", to: "venetian", type: "sidewalk", walkMinutes: 5,
      description: "Walk south along the east sidewalk." },
    { from: "treasure-island", to: "mirage", type: "sidewalk", walkMinutes: 4,
      description: "Walk south along the west sidewalk." },
    { from: "mirage", to: "caesars", type: "sidewalk", walkMinutes: 6,
      description: "Walk south along the west sidewalk past the Mirage entrance." },
    { from: "venetian", to: "harrahs", type: "sidewalk", walkMinutes: 5,
      description: "Walk south along the east sidewalk." },
    { from: "palazzo", to: "venetian", type: "sidewalk", walkMinutes: 2,
      description: "Adjacent on the east side." },
    { from: "harrahs", to: "flamingo", type: "sidewalk", walkMinutes: 3,
      description: "Walk south along the east sidewalk. The LINQ is between them." },
    { from: "flamingo", to: "cromwell", type: "sidewalk", walkMinutes: 2,
      description: "Adjacent properties at the Flamingo Rd corner." },
    { from: "cromwell", to: "paris", type: "sidewalk", walkMinutes: 3,
      description: "Walk south along the east sidewalk." },
    { from: "paris", to: "planet-hollywood", type: "sidewalk", walkMinutes: 4,
      description: "Walk south along the east sidewalk." },
    { from: "caesars", to: "bellagio", type: "sidewalk", walkMinutes: 5,
      description: "Walk south along the west sidewalk past The Forum Shops entrance." },
    { from: "bellagio", to: "cosmopolitan", type: "sidewalk", walkMinutes: 3,
      description: "Walk south along the west sidewalk." },
    { from: "cosmopolitan", to: "aria", type: "sidewalk", walkMinutes: 5,
      description: "Walk south along the west sidewalk through CityCenter." },
    { from: "planet-hollywood", to: "mgm-grand", type: "sidewalk", walkMinutes: 10,
      description: "Walk south along the east sidewalk. Longer stretch with fewer stops." },
    { from: "aria", to: "park-mgm", type: "sidewalk", walkMinutes: 4,
      description: "Walk south along the west sidewalk." },
    { from: "park-mgm", to: "ny-ny", type: "sidewalk", walkMinutes: 3,
      description: "Walk south along the west sidewalk past T-Mobile Arena." },
    { from: "ny-ny", to: "excalibur", type: "sidewalk", walkMinutes: 5,
      description: "Walk south along the west sidewalk across Tropicana Ave." },
    { from: "excalibur", to: "luxor", type: "sidewalk", walkMinutes: 4,
      description: "Walk south along the west sidewalk." },
    { from: "luxor", to: "mandalay-bay", type: "sidewalk", walkMinutes: 5,
      description: "Walk south along the west sidewalk." },
    { from: "mgm-grand", to: "tropicana-site", type: "sidewalk", walkMinutes: 3,
      description: "Walk south along the east sidewalk." },

    // === FREE TRAMS ===
    { from: "mandalay-bay", to: "excalibur", type: "free_tram", walkMinutes: 5, rideName: "Mandalay Bay Tram",
      description: "Free tram from Mandalay Bay to Excalibur, with a stop at Luxor. Note: return trip is express (skips Luxor).",
      stops: ["mandalay-bay", "luxor", "excalibur"],
      hours: "Daily, every 5 minutes" },
    { from: "mandalay-bay", to: "luxor", type: "free_tram", walkMinutes: 3, rideName: "Mandalay Bay Tram",
      description: "Free tram from Mandalay Bay to Luxor (first stop). Note: on return, express skips Luxor.",
      stops: ["mandalay-bay", "luxor", "excalibur"],
      hours: "Daily, every 5 minutes" },
    { from: "bellagio", to: "aria", type: "free_tram", walkMinutes: 5, rideName: "Aria Express",
      description: "Free Aria Express tram connecting Bellagio, Vdara, Crystals, and Park MGM/Aria.",
      stops: ["bellagio", "vdara", "crystals", "aria", "park-mgm"],
      hours: "Daily 8am - 2am, every 7-10 minutes" },
    { from: "bellagio", to: "park-mgm", type: "free_tram", walkMinutes: 7, rideName: "Aria Express",
      description: "Free Aria Express tram from Bellagio to Park MGM, with stops at Vdara and Crystals/Aria.",
      stops: ["bellagio", "vdara", "crystals", "aria", "park-mgm"],
      hours: "Daily 8am - 2am, every 7-10 minutes" },
    { from: "aria", to: "park-mgm", type: "free_tram", walkMinutes: 3, rideName: "Aria Express",
      description: "Free Aria Express tram between Aria and Park MGM.",
      stops: ["bellagio", "vdara", "crystals", "aria", "park-mgm"],
      hours: "Daily 8am - 2am, every 7-10 minutes" },
    { from: "aria", to: "bellagio", type: "free_tram", walkMinutes: 5, rideName: "Aria Express",
      description: "Free Aria Express tram from Aria to Bellagio, with stop at Vdara on return.",
      stops: ["bellagio", "vdara", "crystals", "aria", "park-mgm"],
      hours: "Daily 8am - 2am, every 7-10 minutes" },

    // === MONORAIL (paid, east side of Strip) ===
    { from: "mgm-grand", to: "horseshoe", type: "monorail", walkMinutes: 5, cost: 5,
      rideName: "Las Vegas Monorail",
      description: "Monorail from MGM Grand Station to Horseshoe/Paris Station.",
      hours: "7am-2am weekdays, later on weekends" },
    { from: "horseshoe", to: "flamingo", type: "monorail", walkMinutes: 3, cost: 5,
      rideName: "Las Vegas Monorail",
      description: "Monorail from Horseshoe/Paris Station to Flamingo/LINQ Station.",
      hours: "7am-2am weekdays, later on weekends" },
    { from: "flamingo", to: "harrahs", type: "monorail", walkMinutes: 3, cost: 5,
      rideName: "Las Vegas Monorail",
      description: "Monorail from Flamingo/LINQ Station to Harrah's/The LINQ Station.",
      hours: "7am-2am weekdays, later on weekends" },
    { from: "harrahs", to: "sahara", type: "monorail", walkMinutes: 8, cost: 5,
      rideName: "Las Vegas Monorail",
      description: "Monorail from Harrah's Station to SAHARA Station, passing Convention Center and Westgate stops.",
      hours: "7am-2am weekdays, later on weekends" },
    { from: "mgm-grand", to: "sahara", type: "monorail", walkMinutes: 15, cost: 5,
      rideName: "Las Vegas Monorail",
      description: "Full monorail ride from MGM Grand (south) to SAHARA (north). 7 stations total.",
      hours: "7am-2am weekdays, later on weekends" },
    { from: "sahara", to: "mgm-grand", type: "monorail", walkMinutes: 15, cost: 5,
      rideName: "Las Vegas Monorail",
      description: "Full monorail ride from SAHARA (north) to MGM Grand (south). 7 stations total.",
      hours: "7am-2am weekdays, later on weekends" },
  ],

  monorail: {
    name: "Las Vegas Monorail",
    side: "east",
    cost: "$5 single ride. Day passes available for 1-7 days. Children 5 and under ride free. Nevada residents $1/ride with valid ID.",
    hours: "7am-2am weekdays, extended hours on weekends. Trains every 4-8 minutes.",
    stations: [
      { id: "mgm-grand", name: "MGM Grand Station", nearbyHotels: ["mgm-grand"] },
      { id: "horseshoe", name: "Horseshoe/Paris Station", nearbyHotels: ["horseshoe", "paris"] },
      { id: "flamingo", name: "Flamingo/LINQ Station", nearbyHotels: ["flamingo", "linq", "cromwell"] },
      { id: "harrahs", name: "Harrah's/The LINQ Station", nearbyHotels: ["harrahs", "linq"] },
      { id: "convention-center", name: "Las Vegas Convention Center Station", nearbyHotels: [] },
      { id: "westgate", name: "Westgate Station", nearbyHotels: ["fontainebleau"] },
      { id: "sahara", name: "SAHARA Station", nearbyHotels: ["sahara", "strat"] },
    ]
  },

  freeTrams: [
    {
      name: "Mandalay Bay Tram",
      stops: ["mandalay-bay", "luxor", "excalibur"],
      hours: "Daily, trams every ~5 minutes",
      note: "Return trip from Excalibur to Mandalay Bay is EXPRESS (skips Luxor stop)."
    },
    {
      name: "Aria Express Tram",
      stops: ["bellagio", "vdara", "crystals", "aria", "park-mgm"],
      hours: "Daily 8am - 2am, trams every 7-10 minutes",
      note: "Vdara stop is only on the Bellagio-bound return trip."
    },
    {
      name: "Mirage - Treasure Island Tram",
      stops: ["mirage", "treasure-island"],
      hours: "CURRENTLY CLOSED due to Mirage renovation",
      note: "Suspended indefinitely while The Mirage is converted to Hard Rock Hotel."
    }
  ],

  pedestrianBridges: [
    {
      name: "Spring Mountain / Sands Ave Bridge",
      location: "Spring Mountain Rd / Sands Ave & Las Vegas Blvd",
      connects: ["wynn", "venetian", "treasure-island", "fashion-show"],
      type: "four-corner",
      description: "Four-corner overhead walkway with escalators and elevators."
    },
    {
      name: "Flamingo Road Bridge",
      location: "Flamingo Rd & Las Vegas Blvd",
      connects: ["caesars", "bellagio", "flamingo", "cromwell", "horseshoe"],
      type: "four-corner",
      description: "Four-corner overhead walkway. The Bellagio-Horseshoe bridge is a popular fountain-viewing spot."
    },
    {
      name: "Harmon Ave Bridge",
      location: "Harmon Ave & Las Vegas Blvd",
      connects: ["cosmopolitan", "planet-hollywood"],
      type: "direct",
      description: "Direct pedestrian bridge from Cosmopolitan to Planet Hollywood."
    },
    {
      name: "Tropicana Ave Bridge",
      location: "Tropicana Ave & Las Vegas Blvd",
      connects: ["mgm-grand", "ny-ny", "excalibur", "tropicana-site"],
      type: "four-corner",
      description: "Four-corner overhead walkway. One of the busiest pedestrian intersections on the Strip."
    }
  ],

  tips: [
    "The Strip is 4.2 miles (6.8 km) from the STRAT at the north end to Mandalay Bay at the south end. Walking the entire length takes about 90 minutes without stopping.",
    "Jaywalking fine is $163. Always use crosswalks and pedestrian bridges.",
    "Summer temperatures regularly exceed 110\u00B0F (43\u00B0C). Use indoor walkways and trams to stay cool.",
    "Stay hydrated. Carry water, especially May through September.",
    "Wear comfortable walking shoes. Even short trips involve a lot of walking through large casino floors.",
    "The Monorail runs on the EAST side of the Strip. Stations are behind the hotels, not on Las Vegas Blvd itself. Budget extra walking time to reach stations.",
    "Free trams run on the WEST side of the Strip and are operated by the casinos.",
    "Casino floors are intentionally maze-like. Follow overhead signs to find exits and walkways to connected properties.",
    "The north end of the Strip (STRAT to Resorts World) has fewer connections and longer sidewalk walks between properties.",
    "Peak pedestrian congestion is 6pm-11pm on weekends, especially around the Bellagio fountains and Flamingo Rd intersection."
  ]
};
